database.driver=com.mysql.cj.jdbc.Driver
database.url=jdbc:mysql://localhost:3306/studentsoap_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
database.username=root
database.password=
hibernate.dialect=org.hibernate.dialect.MySQLDialect
hibernate.show_sql=true
hibernate.format_sql=true
hibernate.hbm2ddl.auto=update
